<a href="https://colab.research.google.com/github/DilanOzcan/Python_Math/blob/main/M1_04_Matrix_Transformations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Transformations
Many complex matrix operations cannot be solved eciently or with stability using the limited
precision of computers. Matrix decompositions are methods that reduce a matrix into constituent
parts that make it easier to calculate more complex matrix operations. Matrix decomposition
methods, also called matrix factorization methods, are a foundation of linear algebra in computers,
even for basic operations such as solving systems of linear equations, calculating the inverse, and
calculating the determinant of a matrix.

***What is a Matrix Decomposition?*** A matrix decomposition is a way of reducing a matrix into its constituent parts. It is an
approach that can simplify more complex matrix operations that can be performed on the
decomposed matrix rather than on the original matrix itself. A common analogy for matrix
decomposition is the factoring of numbers, such as the factoring of 10 into $2\times 5$. For this reason,
matrix decomposition is also called matrix factorization. Like factoring real values, there are many ways to decompose a matrix, hence there are a range of different matrix decomposition techniques. Two simple and widely used matrix decomposition methods are the LU matrix
decomposition and the QR matrix decomposition

***LU Decomposition:*** The LU decomposition is for square matrices and decomposes a matrix into L and U components: $A=L\cdot U$, where $A$ is the square matrix that we wish to decompose, $L$ is the lower triangle matrix and $U$ is the upper triangle matrix.

The LU decomposition is found using an iterative numerical process and can fail for those
matrices that cannot be decomposed or decomposed easily. A variation of this decomposition
that is numerically more stable to solve in practice is called the LUP decomposition, or the LU
decomposition with partial pivoting: $A=P\cdot L\cdot U$. The rows of the parent matrix are re-ordered to simplify the decomposition process and the
additional P matrix species a way to permute the result or return the result to the original
order.


The LU decomposition is often used to simplify the solving of systems of linear equations, such as finding the coefficients in a linear regression,
as well as in calculating the determinant and inverse of a matrix.


In [ ]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print('A=',A)
# factorize
P, L, U = lu(A)
print('P=',P)
print('L=',L)
print('U=',U)
# reconstruct
B = P.dot(L).dot(U)
print('B=',B)

A= [[1 2 3]
 [4 5 6]
 [7 8 9]]
P= [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L= [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
U= [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
B= [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
import numpy as np
from scipy.linalg import lu

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A:',A)
print()
P, L, U =lu(A)
print(P)
print()
print(L)
print()
print(U)

A: [[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

[[7.00000000e+00 8.00000000e+00 9.00000000e+00]
 [0.00000000e+00 8.57142857e-01 1.71428571e+00]
 [0.00000000e+00 0.00000000e+00 1.11022302e-16]]


In [ ]:
P@A

array([[4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.]])

In [ ]:
L@U, A

(array([[7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [ ]:
P@L@U

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
P@ (L@U)
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
y=A*X--> X is the data (known), A is the coefficents, y is the target variable (income, known)

y*inv(X)=A*X*inv(X)
y*inv(X)=A*I
y*inv(X)=A
X=L*U

y*inv(U)=A*L*U*inv(U)
a new person, hwose age, education, maritals tstaus, and gender known, income is not known
we want the estimate the income, for that, I need the coefficients

***QR Decomposition:*** The QR decomposition is for $m\times n$ matrices (not limited to square matrices) and decomposes
a matrix into $Q$ and $R$ components: $A=Q\cdot R$.

Where A is the matrix that we wish to decompose, Q a matrix with the size $m\times n$, and R is
an upper triangle matrix with the size $n\times n$. The QR decomposition is found using an iterative
numerical method that can fail for those matrices that cannot be decomposed, or decomposed
easily. Like the LU decomposition, the QR decomposition is often used to solve systems of
linear equations, although is not limited to square matrices.

In [ ]:
m x n * n x n--> m x n

In [ ]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define rectangular matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print('A=',A)
# factorize
Q, R = qr(A)
print('Q=',Q)
print('R=',R)
# reconstruct
B = Q.dot(R)
print('B=',B)

A= [[1 2]
 [3 4]
 [5 6]]
Q= [[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]
R= [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]
B= [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
from numpy import array
import numpy as np
# define rectangular matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

# factorize
Q, R = np.linalg.qr(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(Q)

[[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]


In [ ]:
print(R)

[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]


In [ ]:
Q.dot(R)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
Q @ R

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

***Cholesky Decomposition:*** The Cholesky decomposition is for square symmetric matrices where all eigenvalues are greater
than zero, so-called positive definite matrices where $A=L\cdot L^T$. $A$ is the matrix being decomposed, $L$ is the lower triangular matrix and $L^T$ is the transpose of $L$. The decompose can also be written as the product of the upper triangular
matrix, for example: $A=U^T\cdot U$. The Cholesky decomposition is used for solving
linear least squares for linear regression, as well as simulation and optimization methods. When
decomposing symmetric matrices, the Cholesky decomposition is nearly twice as efficient as the
LU decomposition and should be preferred in these cases.

In [ ]:
#Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define symmetrical matrix
A = array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])
print('A=',A)
# factorize
L = cholesky(A)
print('L=',L)
# reconstruct
B = L.dot(L.T)
print('B=',B)

A= [[2 1 1]
 [1 2 1]
 [1 1 2]]
L= [[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
B= [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


### Eigendecomposition
Matrix decompositions are a useful tool for reducing a matrix to their constituent parts in
order to simplify a range of more complex operations. Perhaps the most used type of matrix
decomposition is the eigendecomposition that decomposes a matrix into eigenvectors and
eigenvalues. This decomposition also plays a role in methods used in machine learning, such
as in the Principal Component Analysis method or PCA.

In [ ]:
f(x, y, z) = a*x + b*y + c*z
x =[1 0 0]
y =[0 1 0]
z =[0 0 1]

x.dot(y)=0

f(x,y,z) = a*[1 0 0]+ b*[0 1 0] + c*[0 0 1]
f(x,y,z) = np.array([a 0 0],[0 b 0],[0 0 c])@np.array([[1 0 0],[0 1 0],[0 0 1]])

f(x,y,z)*x=a*x

In [ ]:
f(x1, x2, x3)=ax1+bx2+cx3
f(x1, x2, x3)= a*(x1, x2=0, x3=0)+b*(x1=0, x2, x3=0)+c*(x1=0, x2=0, x3)
(x1, x2=0, x3=0)
(x1=0, x2, x3=0)
(x1=0, x2=0, x3)


if c is sooo small
f(x1, x2, x3)=g(x1, x2)

In [ ]:
ax1+bx2+cx3 * (1, 0, 0)=a*(1, 0 ,0)
A * eigenvector1 = eigenvalue1 * eignevactor1

In [ ]:
unit vector is a vector with magnitude equals 1
v=(x1, x2)--> magnitude=sqrt(x1^2+x2^2)

for a matrix of size m x n, if m > n, the rank will be at most n

***Eigendecomposition of a Matrix:*** One of the most widely used kinds of matrix decomposition is called eigendecomposition,
in which we decompose a matrix into a set of eigenvectors and eigenvalues.

A vector is an eigenvector of a matrix if it satisfies the following equation: $A\cdot v = \lambda \cdot v$.

This is called the eigenvalue equation, where $A$ is the parent square matrix that we are
decomposing, $v$ is the eigenvector of the matrix, and $\lambda$ is the lowercase Greek letter lambda and
represents the eigenvalue scalar.

In [ ]:
import numpy as np
a=np.array((1,2,3))
np.diag(a)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
import numpy as np
t = np.array([2,5,9])
print(t)
np.diag(t)

[2 5 9]


array([[2, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

$Av_1=\lambda_1 v_1$

$Av_2=\lambda_2 v_2$

$Av_3=\lambda_3 v_3$

$Q=[v_1 v_2 v_3]$

$AQ=Qdiag(\lambda_1, \lambda_2, \lambda_3)$

$A=Qdiag(\lambda_1, \lambda_2, \lambda_3)Q^{-1}$



A matrix could have one eigenvector and eigenvalue for each dimension of the parent matrix.
Not all square matrices can be decomposed into eigenvectors and eigenvalues, and some can
only be decomposed in a way that requires complex numbers. The parent matrix can be shown
to be a product of the eigenvectors and eigenvalues: $A=Q\cdot \Lambda \cdot Q^{-1}$

$Q$ is a matrix of the eigenvectors, $\Lambda$ is the uppercase Greek letter lambda
and is the diagonal matrix comprised of the eigenvalues, and $Q^{-1}$ is the inverse of the matrix
comprised of the eigenvectors.

In [ ]:
A^100= A*A*A..
A^100=(Q*diag(lambda)*inv(Q)) * (Q*diag(lambda)*inv(Q)) * Q*diag(lambda)*inv(Q)..=Q*diag(lambda^100)*inv(Q)

In [ ]:
A^100=A*A*A*.....
A^100=Qdiag(lambda)invQ * Qdiag(lambda)invQ...=Q* diag(lambda)^100 *invQ

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
B.shape-->(200,1000000)-->B=Q*diag(lambda)*inv(Q)-->B_hat=Q_s*diag(lambda_s)*inv(Q_s)

f=1000*x+0.01*y+2*z
f_hat=1000*x

In [ ]:
hyperparamater

I want to recude the dimension of my dataset
100 dimensions,

- create plots of dataset wrt their dimensions, in terms of how much of variancve is explained by each dimension

Eigen is not a name, e.g. the method is not named after $``Eigen''$; eigen (pronounced
eye-gan) is a German word that means own or innate, as in belonging to the parent matrix. A
decomposition operation does not result in a compression of the matrix; instead, it breaks it
down into constituent parts to make certain operations on the matrix easier to perform. Like
other matrix decomposition methods, Eigendecomposition is used as an element to simplify the
calculation of other more complex matrix operations.

Almost all vectors change direction, when they are multiplied by $A$. Certain
exceptional vectors $x$ are in the same direction as $A$x. Those are the "eigenvectors".
Multiply an eigenvector by $A$, and the vector $Ax$ is the number $\lambda$ times the original
$x$.  The eigenvalue $\lambda$ tells whether the special vector $x$ is stretched or shrunk or
reversed or left unchanged when it is multiplied by $A$.

***Eigenvectors and Eigenvalues:*** In general, eigenvectors are unit vectors, which means that their length or magnitude is equal to $1.0$. Eigenvalues are
coefficients applied to eigenvectors that give the vectors their length or magnitude. For example,
a negative eigenvalue may reverse the direction of the eigenvector as part of scaling it. A matrix
that has only positive eigenvalues is referred to as a positive definite matrix, whereas if the
eigenvalues are all negative, it is referred to as a negative definite matrix.

In [ ]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
import numpy as np

B=np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

eigvalues, eigvectors = np.linalg.eig(B)

In [ ]:
#reconstruct matrix
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A:',A)
print()

eig_values, eig_vectors = np.linalg.eig(A)
#print({:.2f}.format(eig_values[:]))
print(eig_values)
print()
print(eig_vectors)

A: [[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
H=0.09867
print(f'{H:.2f}')

0.10


In [ ]:
np.around(eig_values)

array([16., -1., -0.])

In [ ]:
#round(list(eig_values))
[ round(i)for i in eig_values]

[16, -1, 0]

In [ ]:
eig_values[:]

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [ ]:
eig_vectors[:,0].dot(eig_vectors[:,1])

-0.27343437080986494

In [ ]:
values

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [ ]:
diag(values)

array([[ 1.61168440e+01,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.11684397e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.30367773e-15]])

In [ ]:
A@A@A
A=Q*diag(eig)*inv(Q)
Q*diag(eig^3)*inv(Q)

In [ ]:

values, vectors = eig(A)
print(vectors)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
Q * diag(eignevalues)

In [ ]:
values2=values.copy()
values2[2]=0
Q.dot(diag(values2)).dot(R)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
diag(values2)

array([[16.11684397,  0.        ,  0.        ],
       [ 0.        , -1.11684397,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [ ]:
values2

array([16.11684397, -1.11684397,  0.        ])

In [ ]:
from numpy import diag
from numpy.linalg import inv
print(vectors @ diag(values) @ inv(vectors))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
eig_vectors @ np.diag(eig_values) @ np.linalg.inv(eig_vectors)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

We can confirm that a vector is indeed an eigenvector of a matrix. We do this by multiplying
the candidate eigenvector by the value vector and comparing the result with the eigenvalue.

In [ ]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# factorize
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [ ]:
eig_values

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [ ]:
A*v1=lambda1*v1

In [ ]:
B = A @ eig_vectors[:,0]
C = eig_values[0]*eig_vectors[:,0]
print(B)
print()
print(C)

[ -3.73863537  -8.46653421 -13.19443305]

[ -3.73863537  -8.46653421 -13.19443305]


In [ ]:
A*[v1 v2 v3]=[v1 v2 v3]*diag[lambda1 lambda2 lambda3]

A = [v1 v2 v3]*diag[lambda1 lambda2 lambda3] * inv([v1 v2 v3])


### Singular Value Decomposition (SVD)

The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for
reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations
simpler. For the case of simplicity we will focus on the SVD for real-valued matrices and ignore
the case for complex numbers.

$$A=U\cdot \Sigma \cdot V^T$$

Where $A$ is the $m\times n$ matrix that we wish to decompose, $U$ is an $m\times m$ matrix, $\Sigma$ is an $m\times n$ diagonal matrix, and $V^T$ is an $n\times n$ matrix

In [ ]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
import numpy as np
from scipy.linalg import svd

A = np.array([[1,2],[3,4],[5,6]])
print(A)
print()
U, s, VT = svd(A)
print(U)
print()
print(s)
print()
print(VT)

[[1 2]
 [3 4]
 [5 6]]

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

[9.52551809 0.51430058]

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
Sigma = zeros((A.shape[0], A.shape[1]))


# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)

In [ ]:
print(A.shape)
Sigma = np.zeros((A.shape[0], A.shape[1]))
print(Sigma)
print()
print(s)
Sigma[:A.shape[1],:A.shape[1]]=np.diag(s)
print(Sigma)

(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]

[9.52551809 0.51430058]
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


In [ ]:
U@Sigma@VT

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
np.diag(s)

array([[9.52551809, 0.        ],
       [0.        , 0.51430058]])

In [ ]:
# reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
VT@VT.T

array([[1., 0.],
       [0., 1.]])

In [ ]:
transpose:

In [ ]:
U@(U.T)

array([[1.00000000e+00, 2.22044605e-16, 5.55111512e-17],
       [2.22044605e-16, 1.00000000e+00, 1.11022302e-16],
       [5.55111512e-17, 1.11022302e-16, 1.00000000e+00]])

In [ ]:
Sigma = zeros((A.shape[0], A.shape[1]))
Sigma
diag(s)
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
Sigma

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [ ]:
y=B*X
y*inv(X)

X--> our data, rows correspond to subjects, columns to attributes
X may not be a square matrix



***Pseudoinverse:*** The pseudoinverse is the generalization of the matrix inverse for square matrices to rectangular
matrices where the number of rows and columns are not equal.The pseudoinverse is denoted as $A^+$.

$A^+=V\cdot D^+ \cdot U^T$

We can get $U$ and $V$ from SVD operation: $A=U\cdot \Sigma \cdot V^T$.

$D^+$ can be calculated by creating a diagonal matrix from $\Sigma$ and thaking the reciprocal of each non-zero element in $\Sigma$:


\begin{equation}\Sigma = \begin{bmatrix}
  s_{1,1} &  0& 0  \\
  0 & s_{2,2}&0  \\
  0 & 0 &  s_{3,3}  \\
 \end{bmatrix}
\end{equation} and
\begin{equation}D^+ = \begin{bmatrix}
  \frac{1}{s_{1,1}} &  0& 0  \\
  0 & \frac{1}{s_{2,2}}&0  \\
  0 & 0 &  \frac{1}{s_{3,3}}  \\
 \end{bmatrix}
\end{equation}
The pseudoinverse provides one way of solving the linear regression equation, specifically
when there are more rows than there are columns, which is often the case. `NumPy` provides the
function `pinv()` for calculating the pseudoinverse of a rectangular matrix.

In [ ]:
X * inv(X) =I

(U * Sigma * VT) * (V*1/Sigma * UT)

the columns of V re orthogonal to each other
remember eignevectors--> eigenvectors are orthogonal each other

v1*v2-->1

if v1 v2 and v3 are orthogonal
V=[v1 v2 v3]

then V@(V.T)-->I

In [ ]:
# pseudoinverse
from numpy import array
from numpy.linalg import pinv
from numpy import trace
# define matrix
A = array([
[0.1, 0.2],
[0.3, 0.4],
[0.5, 0.6],
[0.7, 0.8]])
print(A)
# calculate pseudoinverse
B = pinv(A)
print(B)
print(A @ B)
trace(A @ B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]
[[ 0.7  0.4  0.1 -0.2]
 [ 0.4  0.3  0.2  0.1]
 [ 0.1  0.2  0.3  0.4]
 [-0.2  0.1  0.4  0.7]]


1.9999999999999971

In [ ]:
import numpy as np
A = np.array([[1,2],[3,4],[5,6],[7,8]])
print(A)
print()
Ainv = np.linalg.pinv(A)
print()
print(Ainv)
print()
--->print(A @ Ainv)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[-1.00000000e+00 -5.00000000e-01  6.34908792e-16  5.00000000e-01]
 [ 8.50000000e-01  4.50000000e-01  5.00000000e-02 -3.50000000e-01]]

[[ 0.7  0.4  0.1 -0.2]
 [ 0.4  0.3  0.2  0.1]
 [ 0.1  0.2  0.3  0.4]
 [-0.2  0.1  0.4  0.7]]


In [ ]:
# pseudoinverse via svd
from numpy import array
from numpy.linalg import svd
from numpy import zeros
from numpy import diag
# define matrix
A = array([
[0.1, 0.2],
[0.3, 0.4],
[0.5, 0.6],
[0.7, 0.8]])
print(A)
# factorize
U, s, VT = svd(A)
# reciprocals of s
d = 1.0 / s
# create m x n D matrix
D = zeros(A.shape)
# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)
# calculate pseudoinverse
B = VT.T.dot(D.T).dot(U.T)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


***Dimentionality Reduction:*** A popular application of SVD is for dimensionality reduction. Data with a large number of
features, such as more features (columns) than observations (rows) may be reduced to a smaller
subset of features that are most relevant to the prediction problem. The result is a matrix with
a lower rank that is said to approximate the original matrix. To do this we can perform an SVD
operation on the original data and select the top $k$ largest singular values in $\Sigma$. These columns
can be selected from $\Sigma$ and the rows selected from $V^T$ . An approximate $B$ of the original vector
A can then be reconstructed.
$$B=U\cdot \Sigma_k \cdot V_k^T$$

***Multiplying A with pseudo inverse of A may not yiled to Identity Matrix***

Let $A \in \Bbb C^{m \times n}$ and $r := \mbox{rank} ({\rm A})$ Let the singular value decomposition (SVD) of $\rm A$ be
$${\rm A} = \begin{bmatrix} {\rm U}_1 &; {\rm U}_2\end{bmatrix} \begin{bmatrix} \Sigma_1 &; {\rm O}\\ {\rm O} &; {\rm O}\end{bmatrix} \begin{bmatrix} {\rm V}_1^*\\ {\rm V}_2^*\end{bmatrix}$$

where $\Sigma_1$ is the $r \times r$ diagonal matrix whose diagonal entries are the positive singular values of $\rm A$. Note that $\rm A$ is invertible — assuming it is not empty, of course. Hence, the pseudo-inverse of $\rm A$ is
$${\rm A}^+ = \begin{bmatrix} {\rm V}_1 &; {\rm V}_2\end{bmatrix} \begin{bmatrix} \Sigma_1^{-1} &; {\rm O}\\ {\rm O} &; {\rm O}\end{bmatrix} \begin{bmatrix} {\rm U}_1^*\\ {\rm U}_2^*\end{bmatrix}$$

and
$${\rm A} {\rm A}^+ = \begin{bmatrix} {\rm U}_1 &; {\rm U}_2\end{bmatrix} \begin{bmatrix} {\rm I}_r &; {\rm O}\\ {\rm O} &; {\rm O}\end{bmatrix} \begin{bmatrix} {\rm U}_1^*\\ {\rm U}_2^*\end{bmatrix} = {\rm U}_1 {\rm U}_1^*$$

is a projection matrix. Note that ${\rm A} {\rm A}^+ = {\rm U}_1 {\rm U}_1^* = {\rm I}_m$ if and only if matrix $\rm A$ has full row rank. Moreover, the trace is

$$\mbox{tr} \left( {\rm A} {\rm A}^+ \right) = \mbox{tr} \left( {\rm U}_1 {\rm U}_1^* \right) = \mbox{tr} \left( {\rm U}_1^* {\rm U}_1 \right) = \mbox{tr} \left( {\rm I}_r \right) = r = \mbox{rank} ({\rm A})$$

Let $\rm P$ be a projection matrix. Then, $\mbox{tr} \left( {\rm P} \right) = \mbox{rank} ({\rm P})$. A very nice property of projection matrices.

In [ ]:
# data reduction with svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)
print()
print(A.shape)
# factorize
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
#Sigma0=Sigma
print('s:',s)
print()
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(VT.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

(3, 10)
s: [9.69657342e+01 7.25578339e+00 6.30452896e-15]

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [ ]:
U * Sigma * VT

In [ ]:
U.shape, Sigma.shape, VT.shape

((3, 3), (3, 2), (2, 10))

In [ ]:
A_hat = resulting matrix has a shape of 3 by 10

In [ ]:
A.shape

(3, 10)

In [ ]:
s

array([9.69657342e+01, 7.25578339e+00, 6.30452896e-15])

In [ ]:
Sigma

array([[96.96573419,  0.        ],
       [ 0.        ,  7.25578339],
       [ 0.        ,  0.        ]])

In [ ]:
VT.dot(VT.T)

array([[ 1.00000000e+00, -5.55111512e-17],
       [-5.55111512e-17,  1.00000000e+00]])

The scikit-learn provides a `TruncatedSVD` class that implements this capability directly. The
`TruncatedSVD` class can be created in which you must specify the number of desirable features
or components to select, e.g. 2. Once created, you can fit the transform (e.g. calculate V T
k ) by calling the `fit()` function, then apply it to the original matrix by calling the transform()
function. The result is the transform of `A` called `T` above. The example below demonstrates the
`TruncatedSVD` class.

In [ ]:
# svd data reduction in scikit-learn
from numpy import array
from sklearn.decomposition import TruncatedSVD
# define matrix
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)
# create transform
svd = TruncatedSVD(n_components=2)
# fit transform
svd.fit(A)
# apply transform
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


In [ ]:
[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]

In [ ]:
with Scikitlearn, you will learn about transformations
e.g., normalize, StandardScaler, MaxMinScaler,.., TruncatedSVD

1. instintiate the transformation object, svd = TruncatedSVD(n_components=2)
2. svd.fit(A)
3. svd now has U, s, VT, svd.transform(A)--> will have a reduced version of A-->A@V

Running the example first prints the defined matrix, followed by the transformed version
of the matrix. We can see that the values match those calculated manually above, except for
the sign on some values. We can expect there to be some instability when it comes to the
sign given the nature of the calculations involved and the differences in the underlying libraries
and methods used. This instability of sign should not be a problem in practice as long as the
transform is trained for reuse.

![image.png](attachment:ebb606cd-94ae-4b49-9eac-ff42d041577f.png)

| Name      | Matrix | Alien  |Star Wars | Casablanca | Titanic|
| :---        |    :----:   |    :----:   |    :----:   |    :----:   |  ---: |
| Joe   | 1| 1|1|0|0|
| Jim   | 3| 3|3|0|0|
| John   | 4| 4|4|0|0|
| Jack   | 5| 5|5|0|0|
| Jill   | 0| 2|0|4|4|
| Jenny   | 0| 0|0|5|5|
| Jane   | 0| 1|0|2|3|


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.linalg import svd as scipy_svd
from sklearn.decomposition import PCA, TruncatedSVD
from numpy.linalg import svd

In [ ]:
# matrix form of the table above
rank = 3
A = np.array([
    [1, 1, 1, 0, 0],
    [3, 3, 3, 0, 0],
    [4, 4, 4, 0, 0],
    [5, 5, 5, 0, 0],
    [0, 2, 0, 4, 4],
    [0, 0, 0, 5, 5],
    [0, 1, 0, 2, 2]])

# we'll use a library to perform the svd
# so we can confirm our result with it
U, S, V = scipy_svd(A, full_matrices = False)
U2, S2, VT2=svd(A)
print(U,S,V)
print()
print(U2,S2, VT2)
svd3 = TruncatedSVD()
svd3_result = svd3.fit_transform(A)
U3 = svd3_result / svd3.singular_values_
S3= svd3.singular_values_#Sigma_matrix = np.diag(svd.singular_values_)
VT3 = svd3.components_
print()
print(U3,S3, VT3)

[[-1.37599126e-01  2.36114514e-02 -1.08084718e-02 -5.60112034e-01
   3.75734575e-01]
 [-4.12797378e-01  7.08343543e-02 -3.24254153e-02 -2.06393278e-01
  -7.55974371e-01]
 [-5.50396503e-01  9.44458057e-02 -4.32338870e-02  7.24808963e-01
   1.84603760e-01]
 [-6.87995629e-01  1.18057257e-01 -5.40423588e-02 -3.43988797e-01
   2.30754700e-01]
 [-1.52775087e-01 -5.91100963e-01  6.53650843e-01 -2.58497890e-16
   2.00000000e-01]
 [-7.22165140e-02 -7.31311857e-01 -6.78209218e-01  0.00000000e+00
   0.00000000e+00]
 [-7.63875433e-02 -2.95550482e-01  3.26825421e-01 -1.29248945e-16
  -4.00000000e-01]] [1.24810147e+01 9.50861406e+00 1.34555971e+00 3.04642685e-16
 0.00000000e+00] [[-5.62258405e-01 -5.92859901e-01 -5.62258405e-01 -9.01335372e-02
  -9.01335372e-02]
 [ 1.26641382e-01 -2.87705846e-02  1.26641382e-01 -6.95376220e-01
  -6.95376220e-01]
 [-4.09667482e-01  8.04791520e-01 -4.09667482e-01 -9.12571001e-02
  -9.12571001e-02]
 [ 7.07106781e-01 -1.11022302e-16 -7.07106781e-01 -5.55111512e-17
   0.

In [ ]:
A.shape

(7, 5)

In [ ]:
U.shape

(7, 5)

In [ ]:
S.shape

(5,)

In [ ]:
S

array([1.24810147e+01, 9.50861406e+00, 1.34555971e+00, 3.04642685e-16,
       0.00000000e+00])

In [ ]:
diag(S)

array([[1.24810147e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 9.50861406e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.34555971e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.04642685e-16,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00]])

In [ ]:
V.shape

(5, 5)

In [ ]:
U2.shape

(7, 7)

In [ ]:
S2.shape

(5,)

In [ ]:
U

array([[-1.37599126e-01,  2.36114514e-02,  1.08084718e-02,
         9.90147543e-01, -1.26568534e-16],
       [-4.12797378e-01,  7.08343543e-02,  3.24254153e-02,
        -5.94088526e-02, -8.85034377e-01],
       [-5.50396503e-01,  9.44458057e-02,  4.32338870e-02,
        -7.92118034e-02,  4.24264069e-01],
       [-6.87995629e-01,  1.18057257e-01,  5.40423588e-02,
        -9.90147543e-02,  1.91609371e-01],
       [-1.52775087e-01, -5.91100963e-01, -6.53650843e-01,
        -9.73880310e-17,  4.77815907e-17],
       [-7.22165140e-02, -7.31311857e-01,  6.78209218e-01,
         4.93038066e-32, -7.10764783e-17],
       [-7.63875433e-02, -2.95550482e-01, -3.26825421e-01,
        -4.86940155e-17, -3.16203559e-17]])

In [ ]:
U2

array([[-1.37599126e-01,  2.36114514e-02,  1.08084718e-02,
         9.90147543e-01, -1.26568534e-16, -1.26568534e-16,
         0.00000000e+00],
       [-4.12797378e-01,  7.08343543e-02,  3.24254153e-02,
        -5.94088526e-02, -8.85034377e-01,  1.91609371e-01,
         0.00000000e+00],
       [-5.50396503e-01,  9.44458057e-02,  4.32338870e-02,
        -7.92118034e-02,  4.24264069e-01,  7.07106781e-01,
         0.00000000e+00],
       [-6.87995629e-01,  1.18057257e-01,  5.40423588e-02,
        -9.90147543e-02,  1.91609371e-01, -6.80651048e-01,
         0.00000000e+00],
       [-1.52775087e-01, -5.91100963e-01, -6.53650843e-01,
        -9.73880310e-17,  4.77815907e-17, -1.00067988e-17,
        -4.47213595e-01],
       [-7.22165140e-02, -7.31311857e-01,  6.78209218e-01,
         4.93038066e-32, -7.10764783e-17,  0.00000000e+00,
         0.00000000e+00],
       [-7.63875433e-02, -2.95550482e-01, -3.26825421e-01,
        -4.86940155e-17, -3.16203559e-17, -5.00339942e-18,
         8.9442719

In [ ]:
print(U2)
print(S2)
print(VT2)

[[-1.37599126e-01  2.36114514e-02  1.08084718e-02  9.90147543e-01
  -1.26568534e-16 -1.26568534e-16  0.00000000e+00]
 [-4.12797378e-01  7.08343543e-02  3.24254153e-02 -5.94088526e-02
  -8.85034377e-01  1.91609371e-01  0.00000000e+00]
 [-5.50396503e-01  9.44458057e-02  4.32338870e-02 -7.92118034e-02
   4.24264069e-01  7.07106781e-01  0.00000000e+00]
 [-6.87995629e-01  1.18057257e-01  5.40423588e-02 -9.90147543e-02
   1.91609371e-01 -6.80651048e-01  0.00000000e+00]
 [-1.52775087e-01 -5.91100963e-01 -6.53650843e-01 -9.73880310e-17
   4.77815907e-17 -1.00067988e-17 -4.47213595e-01]
 [-7.22165140e-02 -7.31311857e-01  6.78209218e-01  4.93038066e-32
  -7.10764783e-17  0.00000000e+00  0.00000000e+00]
 [-7.63875433e-02 -2.95550482e-01 -3.26825421e-01 -4.86940155e-17
  -3.16203559e-17 -5.00339942e-18  8.94427191e-01]]
[1.24810147e+01 9.50861406e+00 1.34555971e+00 1.84716760e-16
 9.74452038e-33]
[[-5.62258405e-01 -5.92859901e-01 -5.62258405e-01 -9.01335372e-02
  -9.01335372e-02]
 [ 1.26641382e-01

![image.png](attachment:fbd4d15e-65c8-4cbf-9264-7fe3bc716f72.png)

| Name      | Matrix | Alien  |Star Wars | Casablanca | Titanic|
| :---        |    :----:   |    :----:   |    :----:   |    :----:   |  ---: |
| Joe   | 1| 1|1|0|0|
| Jim   | 3| 3|3|0|0|
| John   | 4| 4|4|0|0|
| Jack   | 5| 5|5|0|0|
| Jill   | 0| 2|0|4|4|
| Jenny   | 0| 0|0|5|5|
| Jane   | 0| 1|0|2|3|


- The matrix 𝑈 connects people to concept. For example, looking at Joe (the first row in the original matrix). The value 0.13 in the first row and first column of 𝑈 is smaller than some of the other entries in that column. The rationale for this is because while Joe watches only science fiction, he doesn’t rate those movies highly.
- The matrix 𝑉 relates movies to concept. The approximately 0.58 in each of the first three columns of the first row of 𝑉𝑇 indicates that the first three movies – The Matrix, Alien and Star Wars – each are of science-fiction genre.
- Matrix Σ gives the strength of each of the concepts. In our example, the strength of the science-fiction concept is 12.4, while the strength of the romance concept is 9.5. Intuitively, the science-fiction concept is stronger because the data provides more information about the movies of that genre and the people who like them.
- The third concept is a bit harder to interpret, but it doesn't matter that much, because its weight, given by the third nonzero diagonal entry in Σ is relatively low compared to the first two concepts.
- Note that the matrix decomposition doesn't know the meaning of any column in the dataset, it discovers the underlying concept and it is up to us to interpret these latent factors.

| Name      | Matrix | Alien  |Star Wars | Casablanca | Titanic|
| :---        |    :----:   |    :----:   |    :----:   |    :----:   |  ---: |
| Joe   | 1| 1|1|0|0|
| Jim   | 3| 3|3|0|0|
| John   | 4| 4|4|0|0|
| Jack   | 5| 5|5|0|0|
| Jill   | 0| 2|0|4|4|
| Jenny   | 0| 0|0|5|5|
| Jane   | 0| 1|0|2|3|


In [ ]:
# the following cell verifies some properties of SVD

# Verify calculation of A=USV^T
print(np.allclose(A, U @ np.diag(S) @ V)) #np.allclose Returns True if two arrays are element-wise equal within a tolerance.

# orthonormal, columns are unit vectors (length = 1)
print(np.allclose(np.round(np.sum(U * U, axis = 0)), np.ones(S.size)))

# orthogonal, dot product of itself is equivalent to
# the identity matrix U^T U = I
print(np.allclose(U.T @ U, np.eye(S.size)))

True
True
True
