<a href="https://colab.research.google.com/github/DilanOzcan/Python_Math/blob/main/M1_02_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Matrices
In general terms, a matrix is an array of numbers that are arranged into rows and columns.

## Matrices and Matrix Notation
A matrix arranges numbers into rows and columns, like this:

\begin{equation}A = \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
 \end{bmatrix}
\end{equation}

Note that matrices are generally named as a capital letter. We refer to the *elements* of the matrix using the lower case equivalent with a subscript row and column indicator, like this:

\begin{equation}A = \begin{bmatrix}
  a_{1,1} & a_{1,2} & a_{1,3} \\
  a_{2,1} & a_{2,2} & a_{2,3}
 \end{bmatrix}
\end{equation}

In Python, you can define a matrix as a 2-dimensional ***numpy.array***, like this:

In [ ]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
print (A)

[[1 2 3]
 [4 5 6]]


You can also use the ***numpy.matrix*** type, which is a specialist subclass of ***array***:

There are some differences in behavior between ***array*** and ***matrix*** types - particularly with regards to multiplication (which we'll explore later). You can use either, but most experienced Python programmers who need to work with both vectors and matrices tend to prefer the ***array*** type for consistency.

In [ ]:
import numpy as np

M = np.matrix([[1,2,3],
               [4,5,6]])
print (M)

[[1 2 3]
 [4 5 6]]


You can check the shape of a matrix as follows:

In [ ]:
m,n = A.shape
print('m:', m)
print('n:', n)

m: 2
n: 3


If matrix A is expressed as a list of lists, we can get the dimensions of the array using
the len() function as follows.

In [ ]:
A = [[0,1,-2.3,0.1], [1.3, 4, -0.1, 0], [4.1, -1.0, 0, 1.7]]
print('m:', len(A))
print('n:', len(A[0]))
print(A)

m: 3
n: 4
[[0, 1, -2.3, 0.1], [1.3, 4, -0.1, 0], [4.1, -1.0, 0, 1.7]]


***Indexing entries:*** We get the ith row jth column entry of a matrix A using `A[i-1, j-1]` since Python starts indexing from 0.

In [ ]:
A[0,2] #Get the third element in the first row

TypeError: list indices must be integers or slices, not tuple

In [ ]:
A[0][2]

-2.3

In [ ]:
import numpy as np
A = np.array([[0,1,-2.3,0.1], [1.3, 4, -0.1, 0], [4.1, -1.0, 0, 1.7]])
A[0,2] #Get the third element in the first row

-2.3

In [ ]:
A = np.matrix([[0,1,-2.3,0.1], [1.3, 4, -0.1, 0], [4.1, -1.0, 0, 1.7]])
A[0,2] #Get the third element in the first row

-2.3

Below, we create a function to check if a matrix is tall. Note: A `lambda` function is a small anonymous function. A `lambda` function can take any number of arguments, but can only have one expression.

In [ ]:
tall = lambda A: A.shape[0] > A.shape[1]
tall(A)

False

We can also assign a new value to a matrix entry using similar bracket notation.

In [ ]:
A[0,2] = 7.5 #Set the third element in the first row of A to 7.5
A

array([[ 0. ,  1. ,  7.5,  0.1],
       [ 1.3,  4. , -0.1,  0. ],
       [ 4.1, -1. ,  0. ,  1.7]])

***Equality of Matrices:*** `A == B` determines whether the matrices A and B are equal. For numpy arrays A and B, the expression A == B creates a matrix whose entries are Boolean, depending on whether the corresponding entries of A and B are the same. The expression `sum(A == B)` gives the number of entries of A and B that are equal.

In [ ]:
A = np.array([[0,1,-2.3,0.1], [1.3, 4, -0.1, 0], [4.1, -1.0, 0, 1.7]])
B = A.copy()
A == B

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
B[0,3] = 100 #re-assign one of the elements in B
np.sum(A==B)

11

***Row and Column Vectors:*** In Python, there is a subtle difference between a 1D array, a column vector and a row vector.

In [ ]:
# a 3 vector
a = np.array([-2.1, -3, 0])
a.shape

(3,)

In [ ]:
# a 3-vector or a 3 by 1 matrix
b = np.array([[-2.1],[-3],[0]])
b.shape

(3, 1)

In [ ]:
# a 3-row vector or a 1 by 3 matrix
c = np.array([[-2.1, -3, 0]])
c.shape

(1, 3)

You can see `a` has shape (3,), meaning that it is a 1D array, while `b` has shape (3, 1), meaning that it is a 3x1 matrix. This small subtlety generally won't affect you and `b`
can be reshaped to look like `c` easily with the command `b.reshape(1,3)`.

In [ ]:
b.reshape(1,3)

array([[-2.1, -3. ,  0. ]])

***Slicing and submatrices:*** Using colon notation you can extract a submatrix.

In [ ]:
A = np.array([[-1, 0, 1, 0],[2, -3, 0, 1],[0, 4, -2, 1]])
print(A)
A[0:2, 2:4]

[[-1  0  1  0]
 [ 2 -3  0  1]
 [ 0  4 -2  1]]


array([[1, 0],
       [0, 1]])

A very useful shortcut is the index range `:` which refers to the whole index range for that index. This can be used to extract the rows and columns of a matrix.

In [ ]:
# Third column of A
A[:,2]

array([ 1,  0, -2])

In [ ]:
# Second row of A, returned as vector
A[1,:]

array([ 2, -3,  0,  1])

The numpy function `reshape()` gives a new $k\times l$ matrix. (We must have $mn = kl$, i.e., the original and reshaped matrix must have the same number of entries. This is not standard mathematical notation, but they can be useful in Python.

In [ ]:
A.reshape((6,2))

array([[-1,  0],
       [ 1,  0],
       [ 2, -3],
       [ 0,  1],
       [ 0,  4],
       [-2,  1]])

In [ ]:
A.reshape((3,2))

ValueError: cannot reshape array of size 12 into shape (3,2)

***Block matrices:*** We can use the `np.block()` method to construct block matrices in Python. In mathematics, a block matrix or a partitioned matrix is a matrix that is interpreted as having been broken into sections called blocks or submatrices.

In [ ]:
B = np.array([0,2,3]) #1 by 3 matrix
C = np.array([-1]) #1 by 1 matrix
D = np.array([[2,2,1],[1,3,5]]) #2 by 3 matrix
E = np.array([[4],[4]]) #2 by 1 matrix
# Constrcut 3 by 4 block matrix
A = np.block([[B,C],[D,E]])
A

array([[ 0,  2,  3, -1],
       [ 2,  2,  1,  4],
       [ 1,  3,  5,  4]])

***Column and Row Interpretation of a Matrix:*** An $m\times n$ matrix A can be interpreted as a collection of $n$ number of m-vectors (its columns) or a collection of $m$ number of n-row-vectors (its rows). Column vectors can be converted into a matrix using the horizontal function `np.hstack()` and row vectors can be converted into a matrix using the vertical function `np.vstack ()`.

In [ ]:
a = [1,2]
b = [4,5]
c = [7,8]
A = np.vstack([a,b,c])
B = np.hstack([a,b,c])
print('matrix A :',A)
print('dimensions of A :', A.shape)
print('matrix B :',B)
print('dimensions of B :', B.shape)

matrix A : [[1 2]
 [4 5]
 [7 8]]
dimensions of A : (3, 2)
matrix B : [1 2 4 5 7 8]
dimensions of B : (6,)


In [ ]:
a = [[1],[2]]
b = [[4],[5]]
c = [[7],[8]]
A = np.vstack([a,b,c])
B = np.hstack([a,b,c])
print('matrix A :',A)
print('dimensions of A :', A.shape)
print('matrix B :',B)
print('dimensions of B :', B.shape)

matrix A : [[1]
 [2]
 [4]
 [5]
 [7]
 [8]]
dimensions of A : (6, 1)
matrix B : [[1 4 7]
 [2 5 8]]
dimensions of B : (2, 3)


## Matrix Arithmetic

### Matrix Addition/Subtraction

Two matrices with the same dimensions can be added together to create a new third matrix:
$$C=A+B$$

The scalar elements of the resulting matrix are calculated as the addition of the elements in each of the matrices being added:

\begin{equation}C = \begin{bmatrix}
  a_{1,1}+b_{1,1} & a_{1,2}+b_{1,2}  \\
  a_{2,1}+b_{2,1} & a_{2,2}+b_{2,2}  \\
  a_{3,1}+b_{3,1} & a_{3,2}+b_{3,2}  \\
 \end{bmatrix}
\end{equation}
Or we can also say
\begin{align*}
C[0,0]&=A[0,0]+B[0,0] \\
C[1,0]&=A[1,0]+B[1,0] \\
C[2,0]&=A[2,0]+B[2,0] \\
C[0,1]&=A[0,1]+B[0,1] \\
C[1,1]&=A[1,1]+B[1,1] \\
C[2,1]&=A[2,1]+B[2,1] \\
\end{align*}
We can implement this in Python as following:

In [ ]:
# matrix addition
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print('A=',A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print('B=',B)
# add matrices
C = A + B
print('C=',C)

A= [[1 2 3]
 [4 5 6]]
B= [[1 2 3]
 [4 5 6]]
C= [[ 2  4  6]
 [ 8 10 12]]


### Matrix Multiplication (Hadamard Product)/Division

Two matrices with the same size can be multiplied together, and this is often called element-wise
matrix multiplication or the Hadamard product. It is not the typical operation meant when
referring to matrix multiplication, therefore a dierent operator is often used, such as a circle $\circ$
$$C=A\circ B$$

As with element-wise subtraction and addition, element-wise multiplication involves the
multiplication of elements from each parent matrix to calculate the values in the new matrix.

\begin{equation}C = \begin{bmatrix}
  a_{1,1}\times b_{1,1} & a_{1,2}\times b_{1,2}  \\
  a_{2,1}\times b_{2,1} & a_{2,2}\times b_{2,2}  \\
  a_{3,1}\times b_{3,1} & a_{3,2}\times b_{3,2}  \\
 \end{bmatrix}
\end{equation}
Or we can also say
\begin{align*}
C[0,0]&=A[0,0]\times B[0,0] \\
C[1,0]&=A[1,0]\times B[1,0] \\
C[2,0]&=A[2,0]\times B[2,0] \\
C[0,1]&=A[0,1]\times B[0,1] \\
C[1,1]&=A[1,1]\times B[1,1] \\
C[2,1]&=A[2,1]\times B[2,1] \\
\end{align*}
We can implement this in Python as following:

In [ ]:
# matrix addition
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print('A=',A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print('B=',B)
# add matrices
C = A * B
print('C=',C)

A= [[1 2 3]
 [4 5 6]]
B= [[1 2 3]
 [4 5 6]]
C= [[ 1  4  9]
 [16 25 36]]


In [ ]:
# matrix addition
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print('A=',A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print('B=',B)
# add matrices
C = A / B
print('C=',C)

A= [[1 2 3]
 [4 5 6]]
B= [[1 2 3]
 [4 5 6]]
C= [[1. 1. 1.]
 [1. 1. 1.]]


### Matrix-Matrix Multiplication

Matrix multiplication, also called the matrix dot product is more complicated than the previous
operations and involves a rule as not all matrices can be multiplied together.
$$C=A\cdot B$$

The rule for matrix multiplication is that the number of columns (n) in the first matrix (A) must equal the number of rows (m) in
the second matrix (B):
$$C(m,k)=A(m,n)\cdot B(n,k)$$


\begin{equation}A = \begin{bmatrix}
  a_{1,1} & a_{1,2}  \\
  a_{2,1} & a_{2,2}  \\
  a_{3,1} & a_{3,2}  \\
 \end{bmatrix}
\end{equation}

\begin{equation}B = \begin{bmatrix}
  b_{1,1} & b_{1,2}  \\
  b_{2,1} & b_{2,2}  \\
 \end{bmatrix}
\end{equation}

\begin{equation}C = \begin{bmatrix}
  a_{1,1}\times b_{1,1} + a_{1,2}\times b_{2,1}, & a_{1,1}\times b_{1,2} + a_{1,2}\times b_{2,22}   \\
  a_{2,1}\times b_{1,1} + a_{2,2}\times b_{2,1}, & a_{2,1}\times b_{1,2} + a_{2,2}\times b_{2,22}   \\
  a_{3,1}\times b_{1,1} + a_{3,2}\times b_{2,1}, & a_{3,1}\times b_{1,2} + a_{3,2}\times b_{2,22}   \\
 \end{bmatrix}
\end{equation}
Or we can also say
\begin{align*}
C[0,0]&=A[0,0]\times B[0,0]+ A[0,1]\times B[1,0] \\
C[1,0]&=A[1,0]\times B[0,0]+ A[1,1]\times B[1,0] \\
C[2,0]&=A[2,0]\times B[0,0]+ A[2,1]\times B[1,0] \\
C[0,1]&=A[0,0]\times B[0,1]+ A[0,1]\times B[1,1] \\
C[1,1]&=A[1,0]\times B[0,1]+ A[1,1]\times B[1,1] \\
C[2,1]&=A[2,0]\times B[0,1]+ A[2,1]\times B[1,1] \\
\end{align*}

The matrix multiplication operation can be implemented in NumPy using the `dot()` function.
It can also be calculated using the newer `@` operator, since Python version 3.5. The example
below demonstrates both methods.

In [ ]:
# matrix dot product
from numpy import array
# define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print('A=',A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print('B=',B)
# multiply matrices
C = A.dot(B)
print('C=',C)
# multiply matrices with @ operator
D = A @ B
print('D=',D)

A= [[1 2]
 [3 4]
 [5 6]]
B= [[1 2]
 [3 4]]
C= [[ 7 10]
 [15 22]
 [23 34]]
D= [[ 7 10]
 [15 22]
 [23 34]]


### Matrix-Vector Multiplication
A matrix and a vector can be multiplied together as long as the rule of matrix multiplication
is observed. Specifically, that the number of columns in the matrix must equal the number of
items in the vector. As with matrix multiplication, the operation can be written using the dot
notation. Because the vector only has one column, the result is always a vector.
$$c=A\cdot v$$

\begin{equation}A = \begin{bmatrix}
  a_{1,1} & a_{1,2}  \\
  a_{2,1} & a_{2,2}  \\
  a_{3,1} & a_{3,2}  \\
 \end{bmatrix}
\end{equation}

\begin{equation}v = \begin{bmatrix}
  v_{1}   \\
  v_{2}   \\
 \end{bmatrix}
\end{equation}

\begin{equation}c = \begin{bmatrix}
  a_{1,1}\times v_{1} + a_{1,2}\times v_{2}\\
  a_{2,1}\times v_{1} + a_{2,2}\times v_{2}\\
  a_{3,1}\times v_{1} + a_{3,2}\times v_{2}\\
 \end{bmatrix}
\end{equation}
Or we can also say
\begin{align*}
c[0]&=A[0,0]\times v[0]+ A[0,1]\times v[1] \\
c[1]&=A[1,0]\times v[0]+ A[1,1]\times v[1] \\
c[2]&=A[2,0]\times v[0]+ A[2,1]\times v[1] \\
\end{align*}

The matrix-vector multiplication can be implemented in `NumPy` using the `dot()` function.

In [ ]:
# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print('A=',A)
# define vector
B = array([0.5, 0.5])
print('B=',B)
# multiply
C = A.dot(B)
print('C=',C)
D = A @ B
print('D=',D)

A= [[1 2]
 [3 4]
 [5 6]]
B= [0.5 0.5]
C= [1.5 3.5 5.5]
D= [1.5 3.5 5.5]


### Matrix-Scalar Multiplication
A matrix can be multiplied by a scalar. This can be represented using the dot notation between
the matrix and the scalar.
$$C=A\cdot b$$

\begin{equation}A = \begin{bmatrix}
  a_{1,1} & a_{1,2}  \\
  a_{2,1} & a_{2,2}  \\
  a_{3,1} & a_{3,2}  \\
 \end{bmatrix}
\end{equation}


\begin{equation}C = \begin{bmatrix}
  a_{1,1}\times b + a_{1,2}\times b\\
  a_{2,1}\times b + a_{2,2}\times b\\
  a_{3,1}\times b + a_{3,2}\times b\\
 \end{bmatrix}
\end{equation}
Or we can also say
\begin{align*}
C[0,0]&=A[0,0]\times b \\
C[1,0]&=A[1,0]\times b \\
C[2,0]&=A[2,0]\times b \\
C[0,1]&=A[0,0]\times b \\
C[1,1]&=A[1,0]\times b \\
C[2,1]&=A[2,0]\times b \\
\end{align*}

The matrix-vector multiplication can be implemented in `NumPy` using multiplication operator.

In [ ]:
# matrix-scalar multiplication
from numpy import array
# define matrix
A = array([[1, 2], [3, 4], [5, 6]])
print('A=',A)
# define scalar
b = 0.5
print('b=',b)
# multiply
C = A * b
print('C=',C)

A= [[1 2]
 [3 4]
 [5 6]]
b= 0.5
C= [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


## Types of Matrices

***Zero Matrix:*** A zero matrix of size $m\times n$ is created using `np.zeros((m,n))`. Note the double brackets!

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

***Ones Matrix:*** In Python, you can create a matyrix with all entries equal to one by using `np.ones((m,n))`

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

***Square Matrix:*** A square matrix is a matrix where the number of rows (n) is equivalent to the number of
columns (m).

In [ ]:
import numpy as np
x = np.array([[0, 1, 2],
[3, 4, 5],
[6, 7, 8]])
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


***Symmetric Matrix:*** A symmetric matrix is a type of square matrix where the top-right triangle is the same as the
bottom-left triangle.

In [ ]:
x = np.array([[1, 2, 3,4,5],
[2, 1, 2,3,4],
[3,2,1,2,3],
[4,3,2,1,2],
[5,4,3,2,1]])
print(x)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


***Triangular Matrix:*** A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left
of the matrix with the remaining elements filled with zero values. A triangular matrix with
values only above the main diagonal is called an `upper triangular matrix`. Whereas, a triangular
matrix with values only below the main diagonal is called a `lower triangular matrix`.

In [ ]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# lower triangular matrix
lower = tril(M)
print(lower)
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


***Diagonal Matrices:*** A diagonal matrix is one where values outside of the main diagonal have a zero value, where the
main diagonal is taken from the top left of the matrix to the bottom right. A diagonal matrix
is often denoted with the variable D and may be represented as a full matrix or as a vector of
values on the main diagonal.

In [ ]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


Here we can see that, when we apply the `np.diag()` function to a matrix, it extracts
the diagonal elements as a vector (array). When we apply the `np.diag()` function to a
vector (array), it constructs a diagonal matrix with diagonal entries given in the vector.

***Identity Matrix:*** An identity matrix is a square matrix that does not change a vector when multiplied. The
values of an identity matrix are known. All of the scalar values along the main diagonal (top-left
to bottom-right) have the value one, while all other values are zero.
You can also use the `np.identity(n)` function to create an identity matrix of dimension n.

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Another useful expression is `np.c_` and `np.r_`, which allow us to stack column (and row) vectors with other vectors (and matrices).

In [ ]:
np.c_[-np.identity(3), np.zeros((3,1))]

array([[-1., -0., -0.,  0.],
       [-0., -1., -0.,  0.],
       [-0., -0., -1.,  0.]])

In [ ]:
np.r_[np.identity(3), np.zeros((1,3))]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

***Random Matrices:*** A random $m\times n$ matrix with entries distributed uniformly between
0 and 1 is created using `np.random.random((m,n))`. For entries that have a standard
normal distribution, we can use `np.random.normal((m,n))`.

In [ ]:
np.random.random((2,3))

array([[0.33216132, 0.74843679, 0.97110513],
       [0.82645778, 0.41207597, 0.01240686]])

In [ ]:
np.random.randn(3,2)

array([[-1.04357709, -0.71501676],
       [ 2.51052505, -0.43014845],
       [ 1.55412324,  0.83060203]])

***Sparse Matrices:*** Functions for creating and manipulating sparse matrices are contained
in the `scipy.sparse` module, which must be installed and imported. Sparse
matrices are stored in a special format that exploits the property that most of the elements
are zero. The `scipy.sparse.coo_matrix()` function create a sparse matrix from
three arrays that specify the `row indexes`, `column indexes`, and `values` of the nonzero
elements. The following code creates a sparse matrix

\begin{bmatrix}-1.11 &0 &1.17 &0 &0  \\
0.15 &-0.10 &0 &0 &0\\
0 &0 &-0.3 &0 &0\\
0 &0 &0 &0.13 &0\\
\end{bmatrix}

In [ ]:
from scipy import sparse
I = np.array([ 0, 1, 1, 0, 2, 3 ]) # row indexes of nonzeros
J = np.array([ 0, 0, 1, 2, 2, 3 ]) # column indexes
V = np.array([ -1.11, 0.15, -0.10, 1.17, -0.30, 0.13 ]) # values
A = sparse.coo_matrix((V,(I,J)), shape=(4,5))
A

<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in COOrdinate format>

In [ ]:
A.nnz

6

Sparse matrices can be converted to regular non-sparse matrices using the todense()
method.

In [ ]:
A.todense()

matrix([[-1.11,  0.  ,  1.17,  0.  ,  0.  ],
        [ 0.15, -0.1 ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  , -0.3 ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.13,  0.  ]])

***Orthogonal Matrices:*** Two vectors are orthogonal when their dot product equals zero. If the length of each vector is 1
then the vectors are called orthonormal because they are both orthogonal and normalized.
$$v\cdot w=v\cdot w^{T}=0$$

An orthogonal matrix is a square matrix whose rows are mutually orthonormal and
whose columns are mutually orthonormal:

$$Q^T\cdot Q=Q\cdot Q^T=I$$
$$Q^T=Q^{-1}$$

In [ ]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
[1, 0],
[0, -1]])
print('Q=',Q)
# inverse equivalence
V = inv(Q)
print('QT=',Q.T)
print('V=',V)
# identity equivalence
I = Q.dot(Q.T)
print('I=',I)

Q= [[ 1  0]
 [ 0 -1]]
QT= [[ 1  0]
 [ 0 -1]]
V= [[ 1.  0.]
 [-0. -1.]]
I= [[1 0]
 [0 1]]


## Matrix Operations
Matrix operations are used in the description of many machine learning algorithms. Some
operations can be used directly to solve key equations, whereas others provide useful shorthand
or foundation in the description and the use of more complex matrix operations.

***Transpose:*** A defined matrix can be transposed, which creates a new matrix with the number of columns
and rows flipped. This is denoted by the superscript T next to the matrix $A^T$.
\begin{equation}A = \begin{bmatrix}
  1 & 2  \\
  3 & 4  \\
  5 & 6  \\
 \end{bmatrix}
\end{equation}
\begin{equation}A^T = \begin{bmatrix}
  1 & 3 & 5  \\
  2 & 4 & 6  \\
 \end{bmatrix}
\end{equation}

In [ ]:
# transpose matrix
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print('A=',A)
# calculate transpose
C = A.T
print('C=',C)

A= [[1 2]
 [3 4]
 [5 6]]
C= [[1 3 5]
 [2 4 6]]


***Inverse:*** Matrix inversion is a process that finds another matrix that when multiplied with the matrix,
results in an identity matrix. Given a matrix $A$, find matrix $B$, such that $AB=BA=I^n$. A matrix is invertible if there exists another matrix that results in the identity matrix, where not all matrices are invertible. A square matrix that is not invertible is referred to as singular. $A^{-1}$ is primarily useful as a theoretical tool, and should not actually be used in practice for most software applications.

In [ ]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print('A=',A)
# invert matrix
B = inv(A)
print('B=',B)
# multiply A and B
I = A.dot(B)
print('I=',I)

A= [[1. 2.]
 [3. 4.]]
B= [[-2.   1. ]
 [ 1.5 -0.5]]
I= [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


***Trace:*** The trace operator gives the sum of all of the diagonal entries of a matrix. The operation of calculating a trace on a square matrix is described using the notation `tr(A)` where $A$ is the square matrix on which the operation is being performed.

In [ ]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print('A=',A)
# calculate trace
B = trace(A)
print('B=',B)

A= [[1 2 3]
 [4 5 6]
 [7 8 9]]
B= 15


***Determinant:*** The determinant of a square matrix is a scalar representation of the volume of the matrix. It is denoted by the `det(A)` notation or `|A|`, where A is the matrix on which we are calculating the determinant. The determinant of a square matrix is calculated from the elements of the matrix. More technically, the determinant is the product of all the eigenvalues of the matrix. The intuition for the determinant is
that it describes the way a matrix will scale another matrix when they are multiplied together.
For example, a determinant of 1 preserves the space of the other matrix. A determinant of 0 indicates that the matrix cannot be inverted. It tells immediately whether the matrix is invertible. The determinant is a zero when the matrix has no
inverse.

In [ ]:
# matrix determinant
from numpy import array
from numpy.linalg import det, inv
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print('A=',A)
# calculate determinant
B = det(A)
print('B=',B)

A= [[1 2 3]
 [4 5 6]
 [7 8 9]]
B= -9.51619735392994e-16


In [ ]:
inv(A)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

***Rank:*** The rank of a matrix is the estimate of the number of linearly independent rows or columns in
a matrix. The rank of a matrix M is often denoted as the function `rank()`. An intuition for rank is to consider it the number of dimensions spanned by all of the vectors within a matrix. For example, a rank of 0 suggest all vectors span a point, a rank of 1 suggests
all vectors span a line, a rank of 2 suggests all vectors span a two-dimensional plane. The rank
is estimated numerically, often using a matrix decomposition method. A common approach is to
use the Singular-Value Decomposition or SVD for short.

In [ ]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print('v1=',v1)
vr1 = matrix_rank(v1)
print('vr1=',vr1)
# zero rank
v2 = array([0,0,0,0,0])
print('v2=',v2)
vr2 = matrix_rank(v2)
print('vr2=',vr2)

v1= [1 2 3]
vr1= 1
v2= [0 0 0 0 0]
vr2= 0


The next example makes it clear that the rank is not the number of dimensions of the
matrix, but the number of linearly independent directions. Three examples of a 2 x 2 matrix
are provided demonstrating matrices with rank 0, 1 and 2.

In [ ]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print('M0=',M0)
mr0 = matrix_rank(M0)
print('mr0=',mr0)
# rank 1
M1 = array([
[1,2],
[1,2]])
print('M1=',M1)
mr1 = matrix_rank(M1)
print('mr1=',mr1)
# rank 2
M2 = array([
[1,2],
[3,4]])
print('M2=',M2)
mr2 = matrix_rank(M2)
print('mr2=',mr2)

M0= [[0 0]
 [0 0]]
mr0= 0
M1= [[1 2]
 [1 2]]
mr1= 1
M2= [[1 2]
 [3 4]]
mr2= 2
